language: node_js
env:
  matrix:
  - TRAVIS_CI=true
node_js:
- '7'
before_deploy:
- npm run build
- npm run static-pages
cache: yarn
install:
- yarn
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  app: bolg-app
  api_key:
    secure: avL9PCdQwegF0dSbpw5cfcIsIDiDDid4Vlf/N6v1tbbzDuzd4eZ2yUpSDq7DHCrhcfa8+ueqqFAJ8KZ45KsS7GB5iFI8KFc1brvGm7cB/f3XoupFzCgaP5O9+yAUgAre7KjR7ap3iCKlvKzZdGRCu3cs4RhNQjDXXAldPmf5TdnuAVTM0RI+tzZcspKqfYKQzyp/Ji7oxAxeAqrAK5c8SmmIl/olmW8bOb5sG9gUeMdRnVRLZhI7mRb3N/gLvnBSKeTSrbs9mzOhOWzF7Ic9nor+pRmEgKxSM24uvxUGikriJbf9Wqx0kJUEES1pv/pTkYcWPBia9zusLzCHwo6ZZV99+AR5qtClwJ+MbYyDhgks+B8PSA4AlQbsWTjGcdZ9kQoJOTo8k9kNkAsQfeAtYBgqogSlA2Vh30+Y0+HGzKo1uTuUWuQz/y+G/xMuLtZTBWSuLDW7y1gC2FmLiVR2cL33lFy5d8tTFwZfdj6sAjqbR5h4qqhTD28nW/2WHhVka/kyug1gKV85hl/H3Ge9VUD5ftFUKMdufJQsKJ6ZkPCBXkHW9v6em4uknHVCotJpg+IoL/eJRsxqkKcBCK+P8N3SkqNXPN/eEk/9nZ5SFQECfFUzph5hWQJgcrRKpTIZJTs1no0jaa9Z/wgThVCU0NxkIYSNkz49GMdXWYxJyd4=
